name: Test
on:
  push:
    branches: [browserstack]
env:
  BASE_SHA: ${{ github.event.pull_request.base.sha }}
  BASE_SHA_TEST: d5252888bb892368c4e7b93065f74cc6d216c8da # v6 sha (Test only)
  BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_GITHUB_USERNAME }}
  BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_GITHUB_ACCESS_KEY }}
  BROWSERSTACK_BUILD: ${{ github.run_number }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          # Number of commits to fetch. 0 indicates all history for all branches and tags.
          # Pulls all commits (needed for Lerna)
          fetch-depth: 0

      - name: Setup resources and environment
        uses: ./.github/actions/setup
        id: setup

      - name: Install Dependencies
        if: steps.setup.outputs.cache-dependencies-hit != 'true'
        run: npm ci --ignore-scripts --audit=false --fund=false

      - name: Reset NX # temporary
        run: npm run reset

      - name: Build
        if: steps.setup.outputs.cache-build-hit != 'true'
        run: npm run build

  browserstack:
    needs: build
    runs-on: ubuntu-latest
    steps:

      - name: 'BrowserStack Env Setup'  # Invokes the setup-env action
        uses: browserstack/github-actions/setup-env@master
        with:
          username:  ${{ secrets.BROWSERSTACK_GITHUB_USERNAME }}
          access-key: ${{ secrets.BROWSERSTACK_GITHUB_ACCESS_KEY }}

      - name: 'BrowserStack Local Tunnel Setup'  # Invokes the setup-local action
        uses: browserstack/github-actions/setup-local@master
        with:
          local-testing: start
          local-identifier: random

      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup resources and environment
        uses: ./.github/actions/setup

      - name: Test
        run: npm run test:affected -- --base=$BASE_SHA_TEST
        # run: npm run test:all

      - name: 'BrowserStackLocal Stop'  # Terminating the BrowserStackLocal tunnel connection
        uses: browserstack/github-actions/setup-local@master
        with:
          local-testing: stop
