name: Production Release Test

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - name: Configure Git User
        run: |
          git config --global user.email "RefinitivUIDev@refinitiv.com"
          git config --global user.name "refinitiv-ui-dev"

      - name: Commit
        run: |
          git commit --allow-empty -m "Release [skip ci]
          git checkout -b check_released && git push
          sleep 1m
          git checkout v6 && git push

