name: Production Release Test

on:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - name: Configure Git User
        run: |
          git config --global user.email "RefinitivUIDev@refinitiv.com"
          git config --global user.name "refinitiv-ui-dev"

      - name: Create Release Commit
        run: |
          git checkout -b new_release
          echo "Test" >> packages/core/CHANGELOG.md
          git add packages/core/CHANGELOG.md
          git commit -m "chore(release): publish [skip ci]"
          git push --set-upstream origin new_release

      - name: Create PR and Auto Merge
        run: |
          gh pr create --base v6 --head new_release --fill
          gh pr merge new_release --auto --merge --delete-branch
          gh workflow run test.yml --ref new_release
          gh pr checks new_release -w

