name: Production Release Test

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - name: Configure Git User
        run: |
          git config --global user.email "RefinitivUIDev@refinitiv.com"
          git config --global user.name "refinitiv-ui-dev"

      - name: Commit
        run: |
          git commit --allow-empty -m "New Commit [skip ci]


          skip-checks: true
          "
          git push
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

